conda activate dinov2_3

#python Feature_similarity/Gabor_test/dinov2_test_on_gabors_different_area_contour_plot.py
python Feature_similarity/Gabor_test/dinov2_test_on_gabors_different_L_b_contour_plot.py
python Feature_similarity/Gabor_test/dinov2_test_on_gabors_different_rho_contour_plot.py
python Feature_similarity/Gabor_test/dinov2_test_on_gabors_different_rho_contour_plot_RG.py
python Feature_similarity/Gabor_test/dinov2_test_on_gabors_different_rho_contour_plot_YV.py

#python Feature_similarity/Gabor_test/lpips_test_on_gabors_different_area_contour_plot.py
python Feature_similarity/Gabor_test/lpips_test_on_gabors_different_L_b_contour_plot.py
python Feature_similarity/Gabor_test/lpips_test_on_gabors_different_rho_contour_plot.py
python Feature_similarity/Gabor_test/lpips_test_on_gabors_different_rho_contour_plot_RG.py
python Feature_similarity/Gabor_test/lpips_test_on_gabors_different_rho_contour_plot_YV.py

#python Feature_similarity/Gabor_test/plot_dinov2_feature_similarity_different_area_contour.py
python Feature_similarity/Gabor_test/plot_dinov2_feature_similarity_different_L_b_contour.py
python Feature_similarity/Gabor_test/plot_dinov2_feature_similarity_different_rho_contour.py
python Feature_similarity/Gabor_test/plot_dinov2_feature_similarity_different_rho_contour_RG.py
python Feature_similarity/Gabor_test/plot_dinov2_feature_similarity_different_rho_contour_YV.py

#python Feature_similarity/Gabor_test/plot_lpips_feature_similarity_different_area_contour.py
python Feature_similarity/Gabor_test/plot_lpips_feature_similarity_different_L_b_contour.py
python Feature_similarity/Gabor_test/plot_lpips_feature_similarity_different_rho_contour.py
python Feature_similarity/Gabor_test/plot_lpips_feature_similarity_different_rho_contour_RG.py
python Feature_similarity/Gabor_test/plot_lpips_feature_similarity_different_rho_contour_YV.py