import numpy as np
from Band_limit_noise_generator.generate_plot_band_lim_noise import generate_band_lim_noise
from Contrast_masking_generator.generate_plot_contrast_masking import generate_contrast_masking
from Gabor_test_stimulus_generator.generate_plot_gabor_functions_new import generate_gabor_patch
from Supra_contrast_color_generator.generate_plot_supra_contrast_color import generate_supra_contrast_color

NN_model_list = {}